services:
  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile
      secrets:
        - github_token
    image: api-gateway:latest
    container_name: api_gateway_app
    ports:
      - "8088:8088"
    networks:
      - sf_network
    environment:
      - NODE_ENV=production
      - CONFIG_FILE=${CONFIG_FILE}
    volumes:
      - ${CONFIG_FILE}:/config/api_gateway.config.yaml
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:8088/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

secrets:
  github_token:
    file: ./github_token.txt

networks:
  sf_network:
    external: true
